### ISSUE TITLE
Explain how to create a cluster for deploying pharos

### ISSUE THREAD

**Issue by NicolasRouquette** [kontena/pharos-cluster#1013]
**What would you like to be added**:

The "Getting Started" documentation assumes that a cluster already exists to configure the `cluster.yml` file. 

**Why is this needed**:

The instructions in https://pharos.sh/docs/getting-started.html#prepare-nodes-for-kubernetes-cluster are insufficient. What do I do with the `cluster.yml` file and `Vagrant` file?

**Example cluster.yml**:

````
hosts:
  - address: "127.0.0.1"
    user: root
    ssh_key_path: ~/.ssh/id_dsa
    role: master
  - address: "127.0.0.1"
    role: worker
  - address: "127.0.0.1"
    role: worker
network:
  provider: weave
addons:
  ingress-nginx:
    enabled: true
```

Does this make sense at all?

I tried this on my machine (Ubuntu 18.04) and ran into a few problems.

*** missing dependency.

```
pharos up -c cluster.yml
==> KONTENA PHAROS v2.1.5 (Kubernetes v1.12.4)
==> Reading instructions ...
==> Sharpening tools ...
Traceback (most recent call last):
	27: from /__enclose_io_memfs__/lib/ruby/gems/2.5.0/bin/pharos-cluster:23:in `<main>'
	26: from /__enclose_io_memfs__/lib/ruby/gems/2.5.0/bin/pharos-cluster:23:in `load'
	25: from /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.1.5/bin/pharos-cluster:12:in `<top (required)>'
	24: from /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/clamp-1.2.1/lib/clamp/command.rb:132:in `run'
	23: from /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.1.5/lib/pharos/command.rb:16:in `run'
	22: from /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/clamp-1.2.1/lib/clamp/command.rb:63:in `run'
	21: from /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/clamp-1.2.1/lib/clamp/subcommand/execution.rb:11:in `execute'
	20: from /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.1.5/lib/pharos/command.rb:16:in `run'
	19: from /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/clamp-1.2.1/lib/clamp/command.rb:63:in `run'
	18: from /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.1.5/lib/pharos/up_command.rb:19:in `execute'
	17: from /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.1.5/lib/pharos/up_command.rb:19:in `chdir'
	16: from /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.1.5/lib/pharos/up_command.rb:20:in `block in execute'
	15: from /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.1.5/lib/pharos/up_command.rb:33:in `configure'
	14: from /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.1.5/lib/pharos/cluster_manager.rb:55:in `load'
	13: from /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.1.5/lib/pharos/addon_manager.rb:28:in `load_addons'
	12: from /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.1.5/lib/pharos/addon_manager.rb:28:in `each'
	11: from /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.1.5/lib/pharos/addon_manager.rb:29:in `block in load_addons'
	10: from /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.1.5/lib/pharos/addon_manager.rb:29:in `each'
	 9: from /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.1.5/lib/pharos/addon_manager.rb:29:in `block (2 levels) in load_addons'
	 8: from /__enclose_io_memfs__/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 7: from /__enclose_io_memfs__/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 6: from /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.1.5/non-oss/pharos_pro/addons/kontena-lens/addon.rb:3:in `<top (required)>'
	 5: from /__enclose_io_memfs__/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 4: from /__enclose_io_memfs__/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 3: from /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/bcrypt-3.1.12/lib/bcrypt.rb:12:in `<top (required)>'
	 2: from /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/bcrypt-3.1.12/lib/bcrypt.rb:16:in `rescue in <top (required)>'
	 1: from /__enclose_io_memfs__/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/__enclose_io_memfs__/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': pharos: undefined symbol: Init_bcrypt_ext - /__enclose_io_memfs__/lib/ruby/gems/2.5.0/extensions/x86_64-linux/2.5.0-static/bcrypt-3.1.12/bcrypt_ext.so (LoadError)
```

Fixed with: `sudo apt-get install bcrypt`

*** stuck.

```
pharos up -c cluster.yml
==> KONTENA PHAROS v2.1.5 (Kubernetes v1.12.4)
==> Reading instructions ...
==> Sharpening tools ...
==> Check for Pharos upgrade @ localhost
    [localhost] Checking for a new version ...
    [localhost] Already at the latest version
==> Gather host facts @ 127.0.0.1 127.0.0.1 127.0.0.1
    [127.0.0.1] Checking sudo access ...
    [127.0.0.1] Checking sudo access ...
    [127.0.0.1] Checking sudo access ...
rouquett@127.0.0.1's password:rouquett@127.0.0.1's password:root@127.0.0.1's password:
#<Thread:0x0000000004836e78@/__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.1.5/lib/pharos/phase_manager.rb:32 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	5: from /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.1.5/lib/pharos/phase_manager.rb:33:in `block (2 levels) in run_parallel'
	4: from /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.1.5/lib/pharos/phase_manager.rb:52:in `yield_phase_with_retry'
	3: from /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.1.5/lib/pharos/phase_manager.rb:88:in `block in apply'
	2: from /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.1.5/lib/pharos/phases/gather_facts.rb:16:in `call'
	1: from /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.1.5/lib/pharos/phases/gather_facts.rb:21:in `check_sudo'
/__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.1.5/lib/pharos/phases/gather_facts.rb:24:in `rescue in check_sudo': Unable to sudo: sudo: a password is required (Pharos::InvalidHostError)
```

Again, it is unclear to me whether this configuration makes sense at all.
However, the documentation about the Pharos configuration says very little about host requirements.
In particular, it is unclear whether pharos supports running a local cluster.
If it is supported, it would be helpful to explain this.

*** minikube cluster

I created a local cluster with minikube.
I can get the config of the cluster:

```
kubectl config view
apiVersion: v1
clusters:
- cluster:
    certificate-authority: /home/rouquett/.minikube/ca.crt
    server: https://192.168.99.100:8443
  name: minikube
contexts:
- context:
    cluster: minikube
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: /home/rouquett/.minikube/client.crt
    client-key: /home/rouquett/.minikube/client.key
```

So I made a corresponding `cluster.yml`:

```
hosts:
  - address: "1192.168.99.19"
    user: root
    ssh_key_path: ~/.ssh/id_dsa
    role: master
network:
  provider: weave
addons:
  ingress-nginx:
    enabled: true
```

That didn't work either:

````
pharos up -c cluster.yml 
==> KONTENA PHAROS v2.1.5 (Kubernetes v1.12.4)
==> Reading instructions ...
==> Sharpening tools ...
==> Check for Pharos upgrade @ localhost
    [localhost] Checking for a new version ...
    [localhost] Already at the latest version
==> Gather host facts @ 1192.168.99.19
    [1192.168.99.19] Checking sudo access ...
#<Thread:0x000000000388c3d8@/__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.1.5/lib/pharos/phase_manager.rb:32 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	16: from /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.1.5/lib/pharos/phase_manager.rb:33:in `block (2 levels) in run_parallel'
	15: from /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.1.5/lib/pharos/phase_manager.rb:52:in `yield_phase_with_retry'
	14: from /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.1.5/lib/pharos/phase_manager.rb:88:in `block in apply'
	13: from /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.1.5/lib/pharos/phases/gather_facts.rb:16:in `call'
	12: from /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.1.5/lib/pharos/phases/gather_facts.rb:22:in `check_sudo'
	11: from /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.1.5/lib/pharos/phase.rb:36:in `ssh'
	10: from /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.1.5/lib/pharos/configuration/host.rb:89:in `ssh'
	 9: from /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.1.5/lib/pharos/configuration/host.rb:89:in `tap'
	 8: from /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.1.5/lib/pharos/ssh/client.rb:45:in `connect'
	 7: from /__enclose_io_memfs__/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
	 6: from /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.1.5/lib/pharos/ssh/client.rb:53:in `block in connect'
	 5: from /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/net-ssh-5.1.0/lib/net/ssh.rb:242:in `start'
	 4: from /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/net-ssh-5.1.0/lib/net/ssh.rb:242:in `new'
	 3: from /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/net-ssh-5.1.0/lib/net/ssh/transport/session.rb:73:in `initialize'
	 2: from /__enclose_io_memfs__/lib/ruby/2.5.0/socket.rb:631:in `tcp'
	 1: from /__enclose_io_memfs__/lib/ruby/2.5.0/socket.rb:227:in `foreach'
/__enclose_io_memfs__/lib/ruby/2.5.0/socket.rb:227:in `getaddrinfo': getaddrinfo: Name or service not known (SocketError)
ERROR: SocketError : getaddrinfo: Name or service not known
```


<!-- Add here example of the cluster.yml for the relevant parts for this new feature. I.e. how you would see this new feature configured. -->

**Comment by jnummelin** [comment]
@NicolasRouquette Thanks for raising this. There's actually couple different things so I'll address them separately.

### bcrypt

This sounds like a bug in the packaging, the pre-compiled package should container everything that's needed. I'll open up separate issue to track that. https://github.com/kontena/pharos-cluster/issues/1019

### Cluster configuration

Yes, to docs need to be bit more precise on this chapter (`Prepare Nodes for Kubernetes Cluster`)[https://pharos.sh/docs/getting-started.html#prepare-nodes-for-kubernetes-cluster]

In general you need to have the infrastructure (machines or VMs) up-and-running with the [supported](https://pharos.sh/docs/requirements.html) base OS.

Technically you can run everything on single host (also on "localhost"). In that case you need to define a single node cluster as Pharos (and Kubernetes) can run only one role per machine. The configuration page has one example how to run a single node cluster: https://pharos.sh/docs/configuration.html#using-node-taints

--> We'll make some adjustments and clarifications into the getting started guide

### Minikube

Minikube is an "installer" for Kubernetes which provisions a ready-to-run single node cluster for you. Pharos cannot, at least currently, work on top of minikube, instead Pharos needs "empty"* nodes to start with. Also in the minikube cluster.yml there's a mistake in the address `1192.168.99.19`. That's why it fails to connect to the host.

*) Empty as in only the base OS setup according to requirements stated in docs.

**Comment by NicolasRouquette** [comment]
Thanks @jnummelin for the feedback.

Instead of minikube, is it possible to use LXD to create a kubernetes cluster on localhost and use that  to configure pharos' `cluster.yml`?

**Comment by jnummelin** [comment]
> is it possible to use LXD to create a kubernetes cluster on localhost

Theoretically yes. If you can configure the base LXD containers to mimic the environment to a level where Pharos & Kube can make kernel tweaks (we need to load `br_netfilter`) and can run additional layer of docker or crio. I've been trying to do that for our test automation with Docker-in-Docker but the low level configs make it fail miserably. I know Kuberenetes folks run some of their test automation in dind type of setup, so it should be technically possible. But certainly not really an officially supported environment.

For local testing [Vagrant](vagrantup.com) would be much easier approach, although it does use more resources as it runs full VMs. I'm in the process of fine-tuning the docs and the Vagrant example that's linked into from docs. Essentially you'll need to copy (or clone the entire repo) those two files locally and then run:
```sh
$ vagrant up # boots up the VMs
$ pharos up # configures Pharos on the hosts
$ pharos kubeconfig > kubeconfig # get the cluster admin access configuration
$ export KUBECONFIG=kubeconfig # make kubectl and other tools to use the above config
$ kubectl get nodes # check cluster state
```

**Comment by iahmad-khan** [comment]
hi ,

I am getting this error:

```
ERROR: Pharos::ExecError : exec failed with code 1: kubeadm-reconfigure.sh
  bash: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
  /bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
  /etc/profile.d/lang.sh: line 32: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
  + set -eu
  + '[' false = true ']'
  + kubeadm init phase control-plane all --config /tmp/kubeadm.cfg.5192e512a75d1c72641e8e269880aa81
  [control-plane] Using manifest folder "/etc/kubernetes/manifests"
  [control-plane] Creating static Pod manifest for "kube-apiserver"
  [controlplane] Adding extra host path mount "pharos" to "kube-apiserver"
  [controlplane] Adding extra host path mount "k8s-audit-file" to "kube-apiserver"
  [controlplane] Adding extra host path mount "k8s-audit-webhook" to "kube-apiserver"
  [controlplane] Adding extra host path mount "k8s-secrets-config" to "kube-apiserver"
  [controlplane] Adding extra host path mount "pharos" to "kube-controller-manager"
  [control-plane] Creating static Pod manifest for "kube-controller-manager"
  [controlplane] Adding extra host path mount "pharos" to "kube-apiserver"
  [controlplane] Adding extra host path mount "k8s-audit-file" to "kube-apiserver"
  [controlplane] Adding extra host path mount "k8s-audit-webhook" to "kube-apiserver"
  [controlplane] Adding extra host path mount "k8s-secrets-config" to "kube-apiserver"
  [controlplane] Adding extra host path mount "pharos" to "kube-controller-manager"
  [control-plane] Creating static Pod manifest for "kube-scheduler"
  [controlplane] Adding extra host path mount "pharos" to "kube-apiserver"
  [controlplane] Adding extra host path mount "k8s-audit-file" to "kube-apiserver"
  [controlplane] Adding extra host path mount "k8s-audit-webhook" to "kube-apiserver"
  [controlplane] Adding extra host path mount "k8s-secrets-config" to "kube-apiserver"
  [controlplane] Adding extra host path mount "pharos" to "kube-controller-manager"
  + kubeadm init phase mark-control-plane --config /tmp/kubeadm.cfg.5192e512a75d1c72641e8e269880aa81
  [mark-control-plane] Marking the node wp-np3-45 as control-plane by adding the label "node-role.kubernetes.io/master=''"
  [mark-control-plane] Marking the node wp-np3-45 as control-plane by adding the taints [node-role.kubernetes.io/master:NoSchedule]
  error execution phase mark-control-plane: timed out waiting for the conditio
```n

**Comment by iahmad-khan** [comment]
When I rerun , it throws another strange error:

**Comment by jnummelin** [comment]
@iahmad-khan I believe this was case of addresses being mistakenly shared between hosts in cluster.yml? We've opened another issue to track that: #1256

**Comment by iahmad-khan** [comment]
Yes, exactly.

**Comment by iahmad-khan** [comment]
There is one other problem related to proxy.
Can you test the configuration for external proxy works? I had to manually change the kublet service for that.
