### ISSUE TITLE
Upgrade to 2.4.0-beta.1 fails sometimes with "undefined method"

### ISSUE THREAD

**Issue by jakolehm** [kontena/pharos-cluster#1361]
```
==> Configure kube client @ default-master-0
    [default-master-0] Fetching kubectl config ...
ERROR: NoMethodError : undefined method `split' for nil:NilClass
```

**Comment by kke** [comment]
Finally managed to trigger this with sentry on.

![image](https://user-images.githubusercontent.com/224971/58801340-ecaffa80-8612-11e9-9f91-eb1b0b81d546.png)

The backtrace still doesn't show a single `split` anywhere.

I think it could be one of these:

```
/Users/kimmo/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/k8s-client-0.8.3/lib/k8s/resource_client.rb
78:        @resource, @subresource = @api_resource.name.split('/', 2)

/Users/kimmo/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/k8s-client-0.8.3/lib/k8s/transport.rb
191:      content_type, = response.headers['Content-Type'].split(';')
```

Investigating.

**Comment by kke** [comment]
`DEBUG=true` was better.

```
NoMethodError: undefined method `split' for nil:NilClass
  /Users/kimmo/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/k8s-client-0.8.3/lib/k8s/transport.rb:191:in `parse_response'
  /Users/kimmo/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/k8s-client-0.8.3/lib/k8s/transport.rb:274:in `block in requests'
  /Users/kimmo/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/k8s-client-0.8.3/lib/k8s/transport.rb:270:in `map'
  /Users/kimmo/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/k8s-client-0.8.3/lib/k8s/transport.rb:270:in `requests'
  /Users/kimmo/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/k8s-client-0.8.3/lib/k8s/transport.rb:329:in `gets'
  /Users/kimmo/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/k8s-client-0.8.3/lib/k8s/client.rb:150:in `apis'
  /Users/kimmo/Projects/pharos-cluster/lib/pharos/phases/configure_client.rb:43:in `client_prefetch'
  /Users/kimmo/Projects/pharos-cluster/lib/pharos/phases/configure_client.rb:20:in `call'
  /Users/kimmo/Projects/pharos-cluster/lib/pharos/phase_manager.rb:98:in `block in apply'
  /Users/kimmo/Projects/pharos-cluster/lib/pharos/retry.rb:20:in `perform'
  /Users/kimmo/Projects/pharos-cluster/lib/pharos/phase_manager.rb:71:in `block in run_serial'
  /Users/kimmo/Projects/pharos-cluster/lib/pharos/phase_manager.rb:70:in `map'
  /Users/kimmo/Projects/pharos-cluster/lib/pharos/phase_manager.rb:70:in `run_serial'
  /Users/kimmo/Projects/pharos-cluster/lib/pharos/phase_manager.rb:82:in `run'
  /Users/kimmo/Projects/pharos-cluster/lib/pharos/phase_manager.rb:95:in `apply'
  /Users/kimmo/Projects/pharos-cluster/lib/pharos/cluster_manager.rb:157:in `apply_phase'
  /Users/kimmo/Projects/pharos-cluster/lib/pharos/cluster_manager.rb:100:in `apply_phases'
  /Users/kimmo/Projects/pharos-cluster/lib/pharos/up_command.rb:45:in `configure'
  /Users/kimmo/Projects/pharos-cluster/lib/pharos/up_command.rb:29:in `block in execute'
  /Users/kimmo/Projects/pharos-cluster/lib/pharos/up_command.rb:28:in `chdir'
  /Users/kimmo/Projects/pharos-cluster/lib/pharos/up_command.rb:28:in `execute'
  /Users/kimmo/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/clamp-1.2.1/lib/clamp/command.rb:63:in `run'
  /Users/kimmo/Projects/pharos-cluster/lib/pharos/command.rb:31:in `run'
  /Users/kimmo/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/clamp-1.2.1/lib/clamp/subcommand/execution.rb:11:in `execute'
  /Users/kimmo/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/clamp-1.2.1/lib/clamp/command.rb:63:in `run'
  /Users/kimmo/Projects/pharos-cluster/lib/pharos/command.rb:31:in `run'
  /Users/kimmo/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/clamp-1.2.1/lib/clamp/command.rb:132:in `run'
  bin/pharos:13:in `<top (required)>'
```

**Comment by kke** [comment]
Yep, the `response.headers['Content-Type'].split(';')`

**Comment by kke** [comment]
Changing that to `&.split` should take it to the `else` branch:

```ruby
      case content_type
      when 'application/json'
        response_data = Yajl::Parser.parse(response.body)

      when 'text/plain'
        response_data = response.body # XXX: broken if status 2xx
      else
        raise K8s::Error::API.new(method, path, response.status, "Invalid response Content-Type: #{response.headers['Content-Type']}")
      end
```

**Comment by jnummelin** [comment]
I think I saw similar unset content type with some custom cert-manager API registered to kube API
