### ISSUE TITLE
PVC of type RWM with CephFS fail

### ISSUE THREAD

**Issue by HristoA** [kontena/pharos-cluster#1482]
**What happened**:
PVC is all the time with status=Pending

**What you expected to happen**:
PVC from type RWM to be created successfully 

**How to reproduce it (as minimally and precisely as possible)**:
- apply `pvc.yml`

**Anything else we need to know?**:
- Storage class with name: `kontena-storage-fs` search to connect to service with name (yml snippet): ` monitors: 'rook-ceph-mon0:6790,rook-ceph-mon1:6790,rook-ceph-mon2:6790'` but in real life (after successfully Kontena Pharos install) there are only services with names: `rook-ceph-mon-a`, `rook-ceph-mon-b`, `rook-ceph-mon-c` this breaks connection problem.
- One workaround that i apply manual is to create: `rook-ceph-mon0`, `rook-ceph-mon1`, `rook-ceph-mon3` services that are the same as existing one just name is changed to match searched one from `kontena-storage-fs` (to this point all good)

Error logs:
**cephfs-provisioner-xxx***
```logs
2019-09-27T12:56:43.666635467Z I0927 12:56:43.666128       1 controller.go:987] provision "default/test" class "kontena-storage-fs": started
2019-09-27T12:56:43.682068599Z I0927 12:56:43.681188       1 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"test", UID:"418d44e9-e126-11e9-ba6f-9600002dca37", APIVersion:"v1", ResourceVersion:"9485991", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "default/test"
2019-09-27T12:56:44.513557685Z E0927 12:56:44.513135       1 cephfs-provisioner.go:158] failed to provision share "kubernetes-dynamic-pvc-41978954-e126-11e9-a6cd-dea801ed06fc" for "kubernetes-dynamic-user-419789cd-e126-11e9-a6cd-dea801ed06fc", err: exit status 1, output: Traceback (most recent call last):
2019-09-27T12:56:44.513621714Z   File "/usr/local/bin/cephfs_provisioner", line 364, in <module>
2019-09-27T12:56:44.513639973Z     main()
2019-09-27T12:56:44.513653394Z   File "/usr/local/bin/cephfs_provisioner", line 358, in main
2019-09-27T12:56:44.513667432Z     print cephfs.create_share(share, user, size=size)
2019-09-27T12:56:44.513680841Z   File "/usr/local/bin/cephfs_provisioner", line 228, in create_share
2019-09-27T12:56:44.513694922Z     volume = self.volume_client.create_volume(volume_path, size=size, namespace_isolated=not self.ceph_namespace_isolation_disabled)
2019-09-27T12:56:44.513707874Z   File "/usr/local/bin/cephfs_provisioner", line 112, in volume_client
2019-09-27T12:56:44.513720993Z     self._volume_client.connect(None)
2019-09-27T12:56:44.513733894Z   File "/lib/python2.7/site-packages/ceph_volume_client.py", line 458, in connect
2019-09-27T12:56:44.51374801Z     self.rados.connect()
2019-09-27T12:56:44.51376213Z   File "rados.pyx", line 895, in rados.Rados.connect (/home/jenkins-build/build/workspace/ceph-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos7/DIST/centos7/MACHINE_SIZE/huge/release/13.2.1/rpm/el7/BUILD/ceph-13.2.1/build/src/pybind/rados/pyrex/rados.c:9815)
2019-09-27T12:56:44.513805902Z rados.IOError: [errno 5] error connecting to the cluster
2019-09-27T12:56:44.5138572Z W0927 12:56:44.513719       1 controller.go:746] Retrying syncing claim "default/test" because failures 0 < threshold 15
2019-09-27T12:56:44.514265319Z I0927 12:56:44.514018       1 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"test", UID:"418d44e9-e126-11e9-ba6f-9600002dca37", APIVersion:"v1", ResourceVersion:"9485991", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "kontena-storage-fs": exit status 1
2019-09-27T12:56:44.514973422Z E0927 12:56:44.514779       1 controller.go:761] error syncing claim "default/test": failed to provision volume with StorageClass "kontena-storage-fs": exit status 1
2019-09-27T12:56:44.515395802Z I0927 12:56:44.515239       1 controller.go:987] provision "default/test" class "kontena-storage-fs": started
2019-09-27T12:56:44.52517338Z I0927 12:56:44.524779       1 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"test", UID:"418d44e9-e126-11e9-ba6f-9600002dca37", APIVersion:"v1", ResourceVersion:"9485993", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "default/test"
```
**rook-ceph-mon-a--xxx***
```logs
```
**rook-ceph-mon-b--xxx***
```logs
```
**rook-ceph-mon-c--xxx***
```logs
2019-09-27T12:56:40.75990484Z 2019-09-27 12:56:40.755 7f2e55e4a700  0 mon.d@2(peon) e3 handle_command mon_command({"prefix": "mds metadata", "who": "replicafs-a"} v 0) v1
2019-09-27T12:56:40.760567083Z 2019-09-27 12:56:40.755 7f2e55e4a700  0 log_channel(audit) log [DBG] : from='mgr.1205794 10.43.0.19:0/1' entity='mgr.a' cmd=[{"prefix": "mds metadata", "who": "replicafs-a"}]: dispatch
2019-09-27T12:56:41.773125806Z 2019-09-27 12:56:41.767 7f2e55e4a700  0 mon.d@2(peon) e3 handle_command mon_command({"prefix": "mds metadata", "who": "replicafs-a"} v 0) v1
2019-09-27T12:56:41.773183281Z 2019-09-27 12:56:41.767 7f2e55e4a700  0 log_channel(audit) log [DBG] : from='mgr.1205794 10.43.0.19:0/1' entity='mgr.a' cmd=[{"prefix": "mds metadata", "who": "replicafs-a"}]: dispatch
2019-09-27T12:56:42.766094155Z 2019-09-27 12:56:42.763 7f2e55e4a700  0 mon.d@2(peon) e3 handle_command mon_command({"prefix": "mds metadata", "who": "replicafs-a"} v 0) v1
2019-09-27T12:56:42.766153348Z 2019-09-27 12:56:42.763 7f2e55e4a700  0 log_channel(audit) log [DBG] : from='mgr.1205794 10.43.0.19:0/1' entity='mgr.a' cmd=[{"prefix": "mds metadata", "who": "replicafs-a"}]: dispatch
2019-09-27T12:56:43.765642589Z 2019-09-27 12:56:43.763 7f2e55e4a700  0 mon.d@2(peon) e3 handle_command mon_command({"prefix": "mds metadata", "who": "replicafs-a"} v 0) v1
2019-09-27T12:56:43.765675942Z 2019-09-27 12:56:43.763 7f2e55e4a700  0 log_channel(audit) log [DBG] : from='mgr.1205794 10.43.0.19:0/1' entity='mgr.a' cmd=[{"prefix": "mds metadata", "who": "replicafs-a"}]: dispatch
2019-09-27T12:56:44.765827781Z 2019-09-27 12:56:44.763 7f2e55e4a700  0 mon.d@2(peon) e3 handle_command mon_command({"prefix": "mds metadata", "who": "replicafs-a"} v 0) v1
2019-09-27T12:56:44.765913505Z 2019-09-27 12:56:44.763 7f2e55e4a700  0 log_channel(audit) log [DBG] : from='mgr.1205794 10.43.0.19:0/1' entity='mgr.a' cmd=[{"prefix": "mds metadata", "who": "replicafs-a"}]: dispatch
2019-09-27T12:56:45.77103638Z 2019-09-27 12:56:45.767 7f2e55e4a700  0 mon.d@2(peon) e3 handle_command mon_command({"prefix": "mds metadata", "who": "replicafs-a"} v 0) v1
2019-09-27T12:56:45.771097405Z 2019-09-27 12:56:45.767 7f2e55e4a700  0 log_channel(audit) log [DBG] : from='mgr.1205794 10.43.0.19:0/1' entity='mgr.a' cmd=[{"prefix": "mds metadata", "who": "replicafs-a"}]: dispatch
2019-09-27T12:56:46.771487355Z 2019-09-27 12:56:46.767 7f2e55e4a700  0 mon.d@2(peon) e3 handle_command mon_command({"prefix": "mds metadata", "who": "replicafs-a"} v 0) v1
2019-09-27T12:56:46.771535997Z 2019-09-27 12:56:46.767 7f2e55e4a700  0 log_channel(audit) log [DBG] : from='mgr.1205794 10.43.0.19:0/1' entity='mgr.a' cmd=[{"prefix": "mds metadata", "who": "replicafs-a"}]: dispatch
2019-09-27T12:56:47.772928775Z 2019-09-27 12:56:47.767 7f2e55e4a700  0 mon.d@2(peon) e3 handle_command mon_command({"prefix": "mds metadata", "who": "replicafs-a"} v 0) v1
2019-09-27T12:56:47.773223961Z 2019-09-27 12:56:47.767 7f2e55e4a700  0 log_channel(audit) log [DBG] : from='mgr.1205794 10.43.0.19:0/1' entity='mgr.a' cmd=[{"prefix": "mds metadata", "who": "replicafs-a"}]: dispatch
2019-09-27T12:56:48.774238557Z 2019-09-27 12:56:48.771 7f2e55e4a700  0 mon.d@2(peon) e3 handle_command mon_command({"prefix": "mds metadata", "who": "replicafs-a"} v 0) v1
2019-09-27T12:56:48.774292165Z 2019-09-27 12:56:48.771 7f2e55e4a700  0 log_channel(audit) log [DBG] : from='mgr.1205794 10.43.0.19:0/1' entity='mgr.a' cmd=[{"prefix": "mds metadata", "who": "replicafs-a"}]: dispatch
2019-09-27T12:56:49.773395851Z 2019-09-27 12:56:49.767 7f2e55e4a700  0 mon.d@2(peon) e3 handle_command mon_command({"prefix": "mds metadata", "who": "replicafs-a"} v 0) v1
2019-09-27T12:56:49.773462902Z 2019-09-27 12:56:49.767 7f2e55e4a700  0 log_channel(audit) log [DBG] : from='mgr.1205794 10.43.0.19:0/1' entity='mgr.a' cmd=[{"prefix": "mds metadata", "who": "replicafs-a"}]: dispatch
2019-09-27T12:56:50.772925256Z 2019-09-27 12:56:50.767 7f2e55e4a700  0 mon.d@2(peon) e3 handle_command mon_command({"prefix": "mds metadata", "who": "replicafs-a"} v 0) v1
2019-09-27T12:56:50.772965055Z 2019-09-27 12:56:50.767 7f2e55e4a700  0 log_channel(audit) log [DBG] : from='mgr.1205794 10.43.0.19:0/1' entity='mgr.a' cmd=[{"prefix": "mds metadata", "who": "replicafs-a"}]: dispatch
```

After applying `pvc.yml` 2 files are created inside `provision` pod:

**/etc/ceph/ceph.conf"**
```logs
[global]
mon_host = rook-ceph-mon0:6790,rook-ceph-mon1:6790,rook-ceph-mon2:6790
auth_client_required = cephx,none
```

**/etc/ceph/ceph.client.admin.keyring"**
```logs
[client.admin]
key = **************************************** {This is hidden from me for issue only}
caps mds = "allow *"
caps mon = "allow *"
caps osd = "allow *"
```

Created PVC is with status = `Pending` forever and events list show:
```log
failed to provision volume with StorageClass "kontena-storage-fs": exit status 1

waiting for a volume to be created, either by external provisioner "ceph.com/cephfs" or manually created by system administrator

External provisioner is provisioning volume for claim "default/test"
```

PV element is missing of course.

**Environment**:
- Pharos version (use `pharos --version`): 2.4.6
- Cloud provider or hardware configuration: Cloud VPS provider, 3 master/ 3 worker nodes, 40GB SSD each node 
- OS (e.g. from /etc/os-release; both for the client and for the used nodes):
4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Others: 

**pvc.yml:**
```yml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test
  labels:
    app:  test
    chart: "test-0.0.0"
    release: "test"
    heritage: "Tiller"
spec:
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: "1Gi"
  storageClassName: "kontena-storage-fs"
```
**cluster.yml**
```yml
  kontena-storage:
    enabled: true
    data_dir: /home/kontena-storage
    storage:
      use_all_nodes: true
      # It's highly recommended to set directories and/or device_filter,
      # otherwise expanding storage does not work properly (see https://github.com/rook/rook/issues/1957)
      directories:
      - path: /home/ceph
    pool:
      replicated:
        size: 3
    dashboard:
      enabled: true
    filesystem:  # Shared filesystem - ReadWriteMany persistent volumes
      enabled: true
      pool:
        replicated:
          size: 3

```

**Comment by HristoA** [comment]
I do a test of PR and still not working for me.

**Comment by HristoA** [comment]
Hi.
I made test on clear cluster (the same OS and kernel) and after apply manual the PR PVC are created and attached correctly/successfully  to pods. BUT something new popup. When i try to create file (evan with simple command) i receive this:
```sh
bash-4.4# echo "test" > text.txt
bash: echo: write error: Filename too long
bash-4.4# ls -la
total 4
drwxr-xr-x    1 root     root             1 Oct 10 08:52 .
drwxr-xr-x    1 root     root          4096 Oct 10 08:16 ..
-rw-r--r--    1 root     root             0 Oct 10 08:52 text.txt
```
File is created but empty. File is replicated to all pods that use it.
- Pod use `node:10.16.3-alpine` image.
- Host nodes are with type `ext4` 

I think that is related in some way to CephFS but for now not found the reason for this error.
Thanks
