### ISSUE TITLE
Error: exec failed with code 1: kubeadm-renew-certs.sh

### ISSUE THREAD

**Issue by Kerwood** [kontena/pharos-cluster#1502]
**What happened**:
Recently setup a new 3 node cluster with CRI-O as runtime.
When re-running `pharos up` the process loops at `Renewing Kubernetes control-plane certificates`. Nothing has changed in the `cluster.yml` file.

Here's a snippet from `pharos up --debug`
```
[pharos-node01] apiserver cert is up to update: ["pharos-node01", "kubernetes", "kubernetes.default", "kubernetes.default.svc", "kubernetes.default.svc.cluster.local", "localhost", "localhost", "10.96.0.1", "172.20.17.197", "172.20.17.197"]
[pharos-node01] Renewing Kubernetes control-plane certificates ...
172.20.17.197: $ env bash --noprofile --norc -x -c cat\ \>\ /tmp/kubeadm.cfg.3b5c1e04a3f6365400e803b6c86d82c8
172.20.17.197: + cat
172.20.17.197: ! 0
172.20.17.197: $ env bash --noprofile --norc -x -c sudo\ env\ -i\ -\ http_proxy\=\"\$http_proxy\"\ https_proxy\=\"\$https_proxy\"\ no_proxy\=\"\$no_proxy\"\ HTTP_PROXY\=\"\$HTTP_PROXY\"\ HTTPS_PROXY\=\"\$HTTPS_PROXY\"\ NO_PROXY\=\"\$NO_PROXY\"\ FTP_PROXY\=\"\$FTP_PROXY\"\ PATH\=\"\$PATH\"\ CONFIG\=\"/tmp/kubeadm.cfg.3b5c1e04a3f6365400e803b6c86d82c8\"\ UNSET_PROXY\=\"true\"\ bash\ --norc\ --noprofile\ -x\ -s < kubeadm-renew-certs.sh
172.20.17.197: + sudo env -i - http_proxy= https_proxy= no_proxy= HTTP_PROXY= HTTPS_PROXY= NO_PROXY= FTP_PROXY= PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin CONFIG=/tmp/kubeadm.cfg.3b5c1e04a3f6365400e803b6c86d82c8 UNSET_PROXY=true bash --norc --noprofile -x -s
172.20.17.197: + set -eu
172.20.17.197: + '[' true = true ']'
172.20.17.197: + read -r var
172.20.17.197: ++ env
172.20.17.197: ++ grep -i _proxy
172.20.17.197: ++ sed 's/=.*//g'
172.20.17.197: + unset NO_PROXY
172.20.17.197: + read -r var
172.20.17.197: + unset http_proxy
172.20.17.197: + read -r var
172.20.17.197: + unset FTP_PROXY
172.20.17.197: + read -r var
172.20.17.197: + unset UNSET_PROXY
172.20.17.197: + read -r var
172.20.17.197: + unset HTTPS_PROXY
172.20.17.197: + read -r var
172.20.17.197: + unset https_proxy
172.20.17.197: + read -r var
172.20.17.197: + unset no_proxy
172.20.17.197: + read -r var
172.20.17.197: + unset HTTP_PROXY
172.20.17.197: + read -r var
172.20.17.197: + kubeadm init phase certs apiserver --config /tmp/kubeadm.cfg.3b5c1e04a3f6365400e803b6c86d82c8
172.20.17.197: Found multiple CRI sockets, please use --cri-socket to select one: /var/run/dockershim.sock, /var/run/crio/crio.sock
172.20.17.197: ! 1
172.20.17.197: $ env bash --noprofile --norc -x -c sudo\ rm\ /tmp/kubeadm.cfg.3b5c1e04a3f6365400e803b6c86d82c8
172.20.17.197: + sudo rm /tmp/kubeadm.cfg.3b5c1e04a3f6365400e803b6c86d82c8
172.20.17.197: ! 0
[pharos-node01] Error: exec failed with code 1: kubeadm-renew-certs.sh
[pharos-node01]   + sudo env -i - http_proxy= https_proxy= no_proxy= HTTP_PROXY= HTTPS_PROXY= NO_PROXY= FTP_PROXY= PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin CONFIG=/tmp/kubeadm.cfg.3b5c1e04a3f6365400e803b6c86d82c8 UNSET_PROXY=true bash --norc --noprofile -x -s
[pharos-node01]   + set -eu
[pharos-node01]   + '[' true = true ']'
[pharos-node01]   + read -r var
[pharos-node01]   ++ env
[pharos-node01]   ++ grep -i _proxy
[pharos-node01]   ++ sed 's/=.*//g'
[pharos-node01]   + unset NO_PROXY
[pharos-node01]   + read -r var
[pharos-node01]   + unset http_proxy
[pharos-node01]   + read -r var
[pharos-node01]   + unset FTP_PROXY
[pharos-node01]   + read -r var
[pharos-node01]   + unset UNSET_PROXY
[pharos-node01]   + read -r var
[pharos-node01]   + unset HTTPS_PROXY
[pharos-node01]   + read -r var
[pharos-node01]   + unset https_proxy
[pharos-node01]   + read -r var
[pharos-node01]   + unset no_proxy
[pharos-node01]   + read -r var
[pharos-node01]   + unset HTTP_PROXY
[pharos-node01]   + read -r var
[pharos-node01]   + kubeadm init phase certs apiserver --config /tmp/kubeadm.cfg.3b5c1e04a3f6365400e803b6c86d82c8
[pharos-node01]   Found multiple CRI sockets, please use --cri-socket to select one: /var/run/dockershim.sock, /var/run/crio/crio.sock
[pharos-node01]     /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.4.9/lib/pharos/transport/command/local.rb:37:in `block in run!'
[pharos-node01]     /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.4.9/lib/pharos/transport/command/local.rb:36:in `tap'
[pharos-node01]     /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.4.9/lib/pharos/transport/command/local.rb:36:in `run!'
[pharos-node01]     /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.4.9/lib/pharos/transport/base.rb:67:in `block in exec!'
[pharos-node01]     /__enclose_io_memfs__/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
[pharos-node01]     /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.4.9/lib/pharos/transport/base.rb:67:in `exec!'
[pharos-node01]     /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.4.9/lib/pharos/transport/base.rb:82:in `exec_script!'
[pharos-node01]     /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.4.9/lib/pharos/phase.rb:105:in `exec_script'
[pharos-node01]     /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.4.9/lib/pharos/phases/configure_master.rb:70:in `block in reconfigure'
[pharos-node01]     /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.4.9/lib/pharos/transport/tempfile.rb:46:in `run'
[pharos-node01]     /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.4.9/lib/pharos/transport/tempfile.rb:29:in `initialize'
[pharos-node01]     /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.4.9/lib/pharos/transport/base.rb:52:in `new'
[pharos-node01]     /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.4.9/lib/pharos/transport/base.rb:52:in `block in tempfile'
[pharos-node01]     /__enclose_io_memfs__/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
[pharos-node01]     /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.4.9/lib/pharos/transport/base.rb:52:in `tempfile'
[pharos-node01]     /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.4.9/lib/pharos/phases/configure_master.rb:69:in `reconfigure'
[pharos-node01]     /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.4.9/lib/pharos/phases/configure_master.rb:30:in `call'
[pharos-node01]     /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.4.9/lib/pharos/phase_manager.rb:98:in `block in apply'
[pharos-node01]     /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.4.9/lib/pharos/retry.rb:20:in `perform'
[pharos-node01]     /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.4.9/lib/pharos/phase_manager.rb:71:in `block in run_serial'
[pharos-node01]     /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.4.9/lib/pharos/phase_manager.rb:70:in `map'
[pharos-node01]     /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.4.9/lib/pharos/phase_manager.rb:70:in `run_serial'
[pharos-node01]     /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.4.9/lib/pharos/phase_manager.rb:82:in `run'
[pharos-node01]     /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.4.9/lib/pharos/phase_manager.rb:95:in `apply'
[pharos-node01]     /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.4.9/lib/pharos/cluster_manager.rb:157:in `apply_phase'
[pharos-node01]     /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.4.9/lib/pharos/cluster_manager.rb:99:in `apply_phases'
[pharos-node01]     /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.4.9/lib/pharos/up_command.rb:45:in `configure'
[pharos-node01]     /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.4.9/lib/pharos/up_command.rb:29:in `block in execute'
[pharos-node01]     /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.4.9/lib/pharos/up_command.rb:28:in `chdir'
[pharos-node01]     /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.4.9/lib/pharos/up_command.rb:28:in `execute'
[pharos-node01]     /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/clamp-1.2.1/lib/clamp/command.rb:63:in `run'
[pharos-node01]     /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.4.9/lib/pharos/command.rb:25:in `run'
[pharos-node01]     /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/clamp-1.2.1/lib/clamp/subcommand/execution.rb:11:in `execute'
[pharos-node01]     /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/clamp-1.2.1/lib/clamp/command.rb:63:in `run'
[pharos-node01]     /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.4.9/lib/pharos/command.rb:25:in `run'
[pharos-node01]     /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/clamp-1.2.1/lib/clamp/command.rb:132:in `run'
[pharos-node01]     /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/pharos-cluster-2.4.9/bin/pharos:12:in `<top (required)>'
[pharos-node01]     /__enclose_io_memfs__/lib/ruby/gems/2.5.0/bin/pharos:23:in `load'
[pharos-node01]     /__enclose_io_memfs__/lib/ruby/gems/2.5.0/bin/pharos:23:in `<main>'
[pharos-node01] Retrying after 2 seconds (#1) ...
[pharos-node01] Checking if Kubernetes control-plane is already initialized ...
```

**Environment**:
- Pharos version (use `pharos --version`): pharos 2.4.9+oss
- Cloud provider or hardware configuration: Virtual Machines
- OS (e.g. from /etc/os-release; both for the client and for the used nodes): 
    - Server: RHEL Server release 7.7 (Maipo)
    - Client: Fedora 30

**cluster.yml:**
```
hosts:
  - address: 172.20.17.197
    user: root
    role: master
    taints: []
    container_runtime: cri-o
    ssh_key_path: ~/.ssh/id_rsa

  - address: 172.20.17.198
    user: root
    role: master
    taints: []
    container_runtime: cri-o
    ssh_key_path: ~/.ssh/id_rsa

  - address: 172.20.17.199
    user: root
    role: master
    taints: []
    container_runtime: cri-o
    ssh_key_path: ~/.ssh/id_rsa

network: {} # Use Weave networking with default config

addons:
  helm:
    enabled: true
  ingress-nginx:
    enabled: true # Enable Nginx ingress controller
```

**Comment by jakolehm** [comment]
Does master have also Docker installed?

**Comment by Kerwood** [comment]
Nope.. Not on any of the nodes.

```
# docker
-bash: docker: command not found
# yum list installed | grep docker
.. nothing ..
```

**Comment by jakolehm** [comment]
Maybe there is still `/var/run/dockershim.sock` in place? If yes -> remove and try again.

**Comment by Kerwood** [comment]
Nope.. 
I can do a total reinstall of the nodes to see if it's a persistent issue or just something unique ?

**Comment by Kerwood** [comment]
I just setup a new cluster to try and replicate the issue.. I cant.
I guess I skrewed something up on the hosts, installing/remove docker multiple times. 
If you want, you can just close this issue, unless you want some more information.
