### ISSUE TITLE
Pharos::Kube#apply_stack does not sort resource files

### ISSUE THREAD

**Issue by SpComb** [kontena/pharos-cluster#199]
Testing with `docker-compose run pharos-cluster up` with ruby 2.4.3, the results of `Dir.glob` are not sorted. This causes stack resources to fail when applied in the wrong order:

```
==> addons: 167.99.36.141
    Applying addon ingress-nginx ...
kube stack ingress-nginx files from glob: ["/app/lib/pharos/resources/ingress-nginx/default-backend-service.yml", "/app/lib/pharos/resources/ingress-nginx/09-udp-services-configmap.yml", "/app/lib/pharos/resources/ingress-nginx/08-tcp-services-configmap.yml", "/app/lib/pharos/resources/ingress-nginx/06-role-binding.yml", "/app/lib/pharos/resources/ingress-nginx/05-cluster-role-binding.yml", "/app/lib/pharos/resources/ingress-nginx/04-service-account.yml", "/app/lib/pharos/resources/ingress-nginx/03-role.yml", "/app/lib/pharos/resources/ingress-nginx/02-cluster-role.yml", "/app/lib/pharos/resources/ingress-nginx/01-namespace.yml", "/app/lib/pharos/resources/ingress-nginx/07-configmap.yml", "/app/lib/pharos/resources/ingress-nginx/daemonset.yml", "/app/lib/pharos/resources/ingress-nginx/default-backend.yml"]
Module: apply resource: v1/Service/default-http-backend
namespaces "ingress-nginx" not found
/usr/local/bundle/gems/kubeclient-3.0.0/lib/kubeclient/common.rb:116:in `rescue in handle_exception'
/usr/local/bundle/gems/kubeclient-3.0.0/lib/kubeclient/common.rb:106:in `handle_exception'
/usr/local/bundle/gems/kubeclient-3.0.0/lib/kubeclient/common.rb:325:in `create_entity'
/app/lib/pharos/kube.rb:66:in `create_resource'
/app/lib/pharos/kube.rb:164:in `rescue in apply_resource'
/app/lib/pharos/kube.rb:161:in `apply_resource'
/app/lib/pharos/kube.rb:121:in `block in apply_stack'
/app/lib/pharos/kube.rb:115:in `each'
/app/lib/pharos/kube.rb:115:in `apply_stack'
/app/lib/pharos/addon.rb:97:in `apply_stack'
/app/lib/pharos/addons/ingress_nginx.rb:38:in `install'
/app/lib/pharos/addon_manager.rb:35:in `block in apply'
/app/lib/pharos/addon_manager.rb:49:in `block in with_enabled_addons'
/app/lib/pharos/addon_manager.rb:46:in `each'
/app/lib/pharos/addon_manager.rb:46:in `with_enabled_addons'
/app/lib/pharos/addon_manager.rb:31:in `apply'
/app/lib/pharos/up_command.rb:162:in `handle_addons'
/app/lib/pharos/up_command.rb:46:in `block in configure'
/app/lib/pharos/up_command.rb:43:in `chdir'
/app/lib/pharos/up_command.rb:43:in `configure'
/app/lib/pharos/up_command.rb:27:in `execute'
/usr/local/bundle/gems/clamp-1.2.1/lib/clamp/command.rb:63:in `run'
/usr/local/bundle/gems/clamp-1.2.1/lib/clamp/subcommand/execution.rb:11:in `execute'
/usr/local/bundle/gems/clamp-1.2.1/lib/clamp/command.rb:63:in `run'
/usr/local/bundle/gems/clamp-1.2.1/lib/clamp/command.rb:132:in `run'
/app/lib/pharos/root_command.rb:14:in `run'
bin/pharos-cluster:12:in `<main>'
```

**Comment by SpComb** [comment]
It looks like `Dir.glob` may return the files in the right order immediately after a git checkout, but not if you replace the files afterwards:

```
$ ls -U lib/pharos/resources/ingress-nginx/
01-namespace.yml  02-cluster-role.yml  03-role.yml  04-service-account.yml  05-cluster-role-binding.yml  06-role-binding.yml  07-configmap.yml  08-tcp-services-configmap.yml  09-udp-services-configmap.yml  daemonset.yml  default-backend-service.yml  default-backend.yml
$ rm lib/pharos/resources/ingress-nginx/01-namespace.yml
$ git checkout -- lib/pharos/resources/ingress-nginx/01-namespace.yml
$ ls -U lib/pharos/resources/ingress-nginx/
02-cluster-role.yml  03-role.yml  04-service-account.yml  05-cluster-role-binding.yml  06-role-binding.yml  07-configmap.yml  08-tcp-services-configmap.yml  09-udp-services-configmap.yml  daemonset.yml  default-backend-service.yml  default-backend.yml  01-namespace.yml
```

**Comment by jakolehm** [comment]
I think it needs `.sort`.
