### ISSUE TITLE
ConfigureMaster audit config is broken

### ISSUE THREAD

**Issue by SpComb** [kontena/pharos-cluster#203]
#174 broken by the #162 erb refactoring

* `Pharos::Phases::Base#parse_resource_file` is still using sing `Pharos::Erb`
* `Pharos::Phases::ConfigureMaster#install` is using `audit/webhook-config.yml` instead of `*.erb`

```
No such file or directory @ realpath_rec - /app/lib/pharos/resources/audit/webhook-config.yml
/app/lib/pharos/phases/base.rb:23:in `realpath'
/app/lib/pharos/phases/base.rb:23:in `parse_resource_file'
/app/lib/pharos/phases/configure_master.rb:74:in `install'
/app/lib/pharos/phases/configure_master.rb:29:in `call'
/app/lib/pharos/up_command.rb:132:in `handle_masters'
/app/lib/pharos/up_command.rb:46:in `block in configure'
/app/lib/pharos/up_command.rb:45:in `chdir'
/app/lib/pharos/up_command.rb:45:in `configure'
/app/lib/pharos/up_command.rb:25:in `execute'
/usr/local/bundle/gems/clamp-1.2.1/lib/clamp/command.rb:63:in `run'
/usr/local/bundle/gems/clamp-1.2.1/lib/clamp/subcommand/execution.rb:11:in `execute'
/usr/local/bundle/gems/clamp-1.2.1/lib/clamp/command.rb:63:in `run'
/usr/local/bundle/gems/clamp-1.2.1/lib/clamp/command.rb:132:in `run'
/app/lib/pharos/root_command.rb:14:in `run'
bin/pharos-cluster:12:in `<main>'
```

**Comment by jakolehm** [comment]
Fixed in #201
