### ISSUE TITLE
Resource updates are not retried on conflicts

### ISSUE THREAD

**Issue by SpComb** [kontena/pharos-cluster#379]
Other kube operators might be modifying the resources at any time, causing our `GET` => `PUT` operations to fail with conflicts... that is normal and to be expected, and the modification should be retried. Alternatively, just re-run the entire `pharos-cluster up`, but that's pretty heavyweight...

```
==> Configure DNS @ 167.99.39.233
    [167.99.39.233] Patching kube-dns addon with 2 replicas (max-surge 1, max-unavailable 1)...
Operation cannot be fulfilled on deployments.extensions "kube-dns": the object has been modified; please apply your changes to the latest version and try again
/usr/local/bundle/gems/kubeclient-3.0.0/lib/kubeclient/common.rb:116:in `rescue in handle_exception'
/usr/local/bundle/gems/kubeclient-3.0.0/lib/kubeclient/common.rb:106:in `handle_exception'
/usr/local/bundle/gems/kubeclient-3.0.0/lib/kubeclient/common.rb:335:in `update_entity'
/app/lib/pharos/kube/client.rb:48:in `update_resource'
/app/lib/pharos/kube/resource.rb:45:in `update'
/app/lib/pharos/phases/configure_dns.rb:93:in `patch_kubedns'
/app/lib/pharos/phases/configure_dns.rb:9:in `call'
/app/lib/pharos/phase_manager.rb:70:in `block in apply'
/app/lib/pharos/phase_manager.rb:40:in `block in run_serial'
/app/lib/pharos/phase_manager.rb:39:in `map'
/app/lib/pharos/phase_manager.rb:39:in `run_serial'
/app/lib/pharos/phase_manager.rb:51:in `run'
/app/lib/pharos/phase_manager.rb:67:in `apply'
/app/lib/pharos/cluster_manager.rb:106:in `apply_phase'
/app/lib/pharos/cluster_manager.rb:87:in `apply_phases'
/app/lib/pharos/up_command.rb:94:in `configure'
/app/lib/pharos/up_command.rb:41:in `block in execute'
/app/lib/pharos/up_command.rb:40:in `chdir'
/app/lib/pharos/up_command.rb:40:in `execute'
/usr/local/bundle/gems/clamp-1.2.1/lib/clamp/command.rb:63:in `run'
/usr/local/bundle/gems/clamp-1.2.1/lib/clamp/subcommand/execution.rb:11:in `execute'
/usr/local/bundle/gems/clamp-1.2.1/lib/clamp/command.rb:63:in `run'
/usr/local/bundle/gems/clamp-1.2.1/lib/clamp/command.rb:132:in `run'
/app/lib/pharos/root_command.rb:14:in `run'
bin/pharos-cluster:12:in `<main>'
```

**Comment by jakolehm** [comment]
> it could be rewritten to just use PATCH instead to avoid the need for retries, if the changes do not depend on the current state of the resource?

Patch acted a bit weird on some cases.

**Comment by jnummelin** [comment]
I think we can close this. There's now retry baked in to phases and addons, plus there's fixes in k8s-client too
