### ISSUE TITLE
pharos-cluster version throws "uninitialized constant"

### ISSUE THREAD

**Issue by jakolehm** [kontena/pharos-cluster#521]
```
pharos-cluster version
Kontena Pharos:
  - pharos-cluster version 1.3.0-beta.2
uninitialized constant Pharos::PhaseManager::OpenSSL
```

**Comment by SpComb** [comment]
The `PhaseManager` is relying on the `Pharos::Kube` autoload => `require 'k8s-client'` dependencies.

```
$ pharos-cluster reset
==> KONTENA PHAROS v1.3.0-beta.2 (Kubernetes v1.11.1)
==> Reading instructions ...
==> Sharpening tools ...
uninitialized constant Pharos::PhaseManager::OpenSSL
/app/lib/pharos/phase_manager.rb:8:in `<class:PhaseManager>'
/app/lib/pharos/phase_manager.rb:4:in `<module:Pharos>'
/app/lib/pharos/phase_manager.rb:3:in `<top (required)>'
/usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/app/lib/pharos/cluster_manager.rb:38:in `load'
/app/lib/pharos/reset_command.rb:30:in `reset'
/app/lib/pharos/reset_command.rb:12:in `block in execute'
/app/lib/pharos/reset_command.rb:11:in `chdir'
/app/lib/pharos/reset_command.rb:11:in `execute'
/usr/local/bundle/gems/clamp-1.2.1/lib/clamp/command.rb:63:in `run'
/usr/local/bundle/gems/clamp-1.2.1/lib/clamp/subcommand/execution.rb:11:in `execute'
/usr/local/bundle/gems/clamp-1.2.1/lib/clamp/command.rb:63:in `run'
/usr/local/bundle/gems/clamp-1.2.1/lib/clamp/command.rb:132:in `run'
/app/lib/pharos/root_command.rb:16:in `run'
bin/pharos-cluster:12:in `<main>'
$ pharos-cluster reset
==> KONTENA PHAROS v1.3.0-beta.2 (Kubernetes v1.11.1)
==> Reading instructions ...
==> Sharpening tools ...
uninitialized constant Pharos::PhaseManager::Excon
/app/lib/pharos/phase_manager.rb:11:in `<class:PhaseManager>'
/app/lib/pharos/phase_manager.rb:6:in `<module:Pharos>'
/app/lib/pharos/phase_manager.rb:5:in `<top (required)>'
/usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/app/lib/pharos/cluster_manager.rb:38:in `load'
/app/lib/pharos/reset_command.rb:30:in `reset'
/app/lib/pharos/reset_command.rb:12:in `block in execute'
/app/lib/pharos/reset_command.rb:11:in `chdir'
/app/lib/pharos/reset_command.rb:11:in `execute'
/usr/local/bundle/gems/clamp-1.2.1/lib/clamp/command.rb:63:in `run'
/usr/local/bundle/gems/clamp-1.2.1/lib/clamp/subcommand/execution.rb:11:in `execute'
/usr/local/bundle/gems/clamp-1.2.1/lib/clamp/command.rb:63:in `run'
/usr/local/bundle/gems/clamp-1.2.1/lib/clamp/command.rb:132:in `run'
/app/lib/pharos/root_command.rb:16:in `run'
bin/pharos-cluster:12:in `<main>'
```
