### ISSUE TITLE
IPAddr::InvalidAddressError : invalid address Error on setting up the cluster

### ISSUE THREAD

**Issue by premdass** [kontena/pharos-cluster#614]
Hi,

I am trying to setup pharos cluster on ubuntu 18.04 a, getting the following error 

```
    # nameserver config
    nameserver 213.133.100.100
    nameserver 213.133.98.98
    nameserver 213.133.99.99
    nameserver 2a01:4f8:0:1::add:1010
    nameserver 2a01:4f8:0:1::add:9898
    nameserver 2a01:4f8:0:1::add:9999
    ! 0
invalid address
/__enclose_io_memfs__/lib/ruby/2.4.0/ipaddr.rb:563:in `in6_addr'
/__enclose_io_memfs__/lib/ruby/2.4.0/ipaddr.rb:500:in `initialize'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-1.3.2/lib/pharos/phases/gather_facts.rb:118:in `new'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-1.3.2/lib/pharos/phases/gather_facts.rb:118:in `block in check_resolvconf_nameserver_localhost'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-1.3.2/lib/pharos/phases/gather_facts.rb:118:in `map'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-1.3.2/lib/pharos/phases/gather_facts.rb:118:in `check_resolvconf_nameserver_localhost'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-1.3.2/lib/pharos/phases/gather_facts.rb:132:in `read_resolvconf'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-1.3.2/lib/pharos/phases/gather_facts.rb:29:in `gather_host_facts'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-1.3.2/lib/pharos/phases/gather_facts.rb:14:in `call'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-1.3.2/lib/pharos/phase_manager.rb:92:in `block in apply'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-1.3.2/lib/pharos/phase_manager.rb:53:in `yield_phase_with_retry'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-1.3.2/lib/pharos/phase_manager.rb:34:in `block (2 levels) in run_parallel'
```
Does it have something to do with IPv6/6 ?

**Comment by kke** [comment]
No, it seems to be a bug in Pharos.

For a quick fix, remove the first comment line from `/etc/resolv.conf`

The problem is the unanchored `/nameserver (.*)/` in https://github.com/kontena/pharos-cluster/blob/master/lib/pharos/phases/gather_facts.rb#L105

**Comment by premdass** [comment]
Thanks.. Removing the comment fixed the issue.
