### ISSUE TITLE
Pharos ssh crashes without options/command

### ISSUE THREAD

**Issue by christofferh** [kontena/pharos-cluster#791]
```
➜  pharos ssh
==> Reading instructions ...
Invalid configuration:
---
:hosts:
- must be filled
- size cannot be less than 1
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-2.0.0.rc.4/lib/pharos/config_schema.rb:35:in `load'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-2.0.0.rc.4/lib/pharos/config.rb:30:in `load'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-2.0.0.rc.4/lib/pharos/command_options/load_config.rb:48:in `load_config'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-2.0.0.rc.4/lib/pharos/command_options/filtered_hosts.rb:25:in `filtered_hosts'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-2.0.0.rc.4/lib/pharos/ssh_command.rb:26:in `run_interactive'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-2.0.0.rc.4/lib/pharos/ssh_command.rb:15:in `execute'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/clamp-1.2.1/lib/clamp/command.rb:63:in `run'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/clamp-1.2.1/lib/clamp/subcommand/execution.rb:11:in `execute'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/clamp-1.2.1/lib/clamp/command.rb:63:in `run'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/clamp-1.2.1/lib/clamp/command.rb:132:in `run'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-2.0.0.rc.4/lib/pharos/root_command.rb:20:in `run'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-2.0.0.rc.4/bin/pharos-cluster:13:in `<top (required)>'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/bin/pharos-cluster:23:in `load'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/bin/pharos-cluster:23:in `<main>'
```

**Comment by kke** [comment]
Quite similar with every command. Only happens when you have a `cluster.yml` file that does not define `hosts:`. Only the `ssh` command prints out the backtrace though.
