### ISSUE TITLE
Upgrading to pharos-cluster 2.0.2 fails on ingress-nginx

### ISSUE THREAD

**Issue by jakubknejzlik** [kontena/pharos-cluster#841]
**What happened**:

While upgrading to pharos-cluster 2.0.2 (same happens to version 2.0.3) I receive following error during ingress-nginx update:

```
==> Enabling addon ingress-nginx
got error (K8s::Error::InternalError): PATCH /api/v1/namespaces/ingress-nginx/configmaps/nginx-configuration => HTTP 500 Internal Server Error: jsonpatch replace operation does not apply: doc is missing key: /data
retrying after xx seconds ...
```

debug output:
```
==> Enabling addon ingress-nginx
I, [2018-11-25T12:46:48.686441 #11742]  INFO -- K8s::Transport<https://xxx:6443>: [GET /api/v1/namespaces/ingress-nginx, GET /apis/rbac.authorization.k8s.io/v1beta1/clusterroles/nginx-ingress-clusterrole, GET /apis/rbac.authorization.k8s.io/v1beta1/namespaces/ingress-nginx/roles/nginx-ingress-role, GET /api/v1/namespaces/ingress-nginx/serviceaccounts/nginx-ingress-serviceaccount, GET /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings/nginx-ingress-clusterrole-nisa-binding, GET /apis/rbac.authorization.k8s.io/v1/namespaces/ingress-nginx/rolebindings/ingress-nginx-psp, GET /apis/rbac.authorization.k8s.io/v1beta1/namespaces/ingress-nginx/rolebindings/nginx-ingress-role-nisa-binding, GET /api/v1/namespaces/ingress-nginx/configmaps/nginx-configuration, GET /api/v1/namespaces/ingress-nginx/configmaps/tcp-services, GET /api/v1/namespaces/ingress-nginx/configmaps/udp-services, GET /apis/extensions/v1beta1/namespaces/ingress-nginx/daemonsets/nginx-ingress-controller, GET /api/v1/namespaces/ingress-nginx/services/default-http-backend, GET /apis/extensions/v1beta1/namespaces/ingress-nginx/deployments/default-http-backend] => HTTP [200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200] in 0.352s
I, [2018-11-25T12:46:48.686952 #11742]  INFO -- Pharos::Kube::Stack<ingress-nginx>: Keep resource v1:Namespace/ingress-nginx in namespace  with checksum=f72695e97bd1b24932cdbb93a2a6f98a
I, [2018-11-25T12:46:48.687272 #11742]  INFO -- Pharos::Kube::Stack<ingress-nginx>: Keep resource rbac.authorization.k8s.io/v1beta1:ClusterRole/nginx-ingress-clusterrole in namespace  with checksum=0326a779b9849baea95ac38d9e7067b4
I, [2018-11-25T12:46:48.687556 #11742]  INFO -- Pharos::Kube::Stack<ingress-nginx>: Keep resource rbac.authorization.k8s.io/v1beta1:Role/nginx-ingress-role in namespace ingress-nginx with checksum=1ec673f2e67a28a9ed7156cb33a705cd
I, [2018-11-25T12:46:48.687717 #11742]  INFO -- Pharos::Kube::Stack<ingress-nginx>: Keep resource v1:ServiceAccount/nginx-ingress-serviceaccount in namespace ingress-nginx with checksum=926a00d0bf96680a915d43837e2abe63
I, [2018-11-25T12:46:48.687934 #11742]  INFO -- Pharos::Kube::Stack<ingress-nginx>: Keep resource rbac.authorization.k8s.io/v1beta1:ClusterRoleBinding/nginx-ingress-clusterrole-nisa-binding in namespace  with checksum=eb8b57774f3bc195bc580493365a62f8
I, [2018-11-25T12:46:48.688134 #11742]  INFO -- Pharos::Kube::Stack<ingress-nginx>: Keep resource rbac.authorization.k8s.io/v1:RoleBinding/ingress-nginx-psp in namespace ingress-nginx with checksum=1a6566ed6a605990419bc4fcce5206e5
I, [2018-11-25T12:46:48.688321 #11742]  INFO -- Pharos::Kube::Stack<ingress-nginx>: Keep resource rbac.authorization.k8s.io/v1beta1:RoleBinding/nginx-ingress-role-nisa-binding in namespace ingress-nginx withchecksum=0226c0a2026e5b1a91d7a98a27508984
I, [2018-11-25T12:46:48.688471 #11742]  INFO -- Pharos::Kube::Stack<ingress-nginx>: Update resource v1:ConfigMap/nginx-configuration in namespace ingress-nginx with checksum=50cb2bc743f4c8849fbb485cc67c8d17
W, [2018-11-25T12:46:48.741443 #11742]  WARN -- K8s::Transport<https://xxx:6443>: PATCH /api/v1/namespaces/ingress-nginx/configmaps/nginx-configuration <Array> => HTTP 500 Internal Server Error in 0.051s
    got error (K8s::Error::InternalError): PATCH /api/v1/namespaces/ingress-nginx/configmaps/nginx-configuration => HTTP 500 Internal Server Error: jsonpatch replace operation does not apply: doc is missing key: /data
    /__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/k8s-client-0.4.2/lib/k8s/transport.rb:192:in `parse_response'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/k8s-client-0.4.2/lib/k8s/transport.rb:210:in `request'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/k8s-client-0.4.2/lib/k8s/resource_client.rb:253:in `json_patch'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/k8s-client-0.4.2/lib/k8s/client.rb:176:in `patch_resource'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/k8s-client-0.4.2/lib/k8s/stack.rb:92:in `block in apply'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/k8s-client-0.4.2/lib/k8s/stack.rb:84:in `map'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/k8s-client-0.4.2/lib/k8s/stack.rb:84:in `apply'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-2.0.2/lib/pharos/addon.rb:233:in `apply_resources'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-2.0.2/addons/ingress-nginx/addon.rb:28:in`block (2 levels) in <top (required)>'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-2.0.2/lib/pharos/addon.rb:189:in `instance_eval'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-2.0.2/lib/pharos/addon.rb:189:in `apply_install'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-2.0.2/lib/pharos/addon.rb:177:in `apply'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-2.0.2/lib/pharos/cluster_manager.rb:178:in `block in apply_addons'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-2.0.2/lib/pharos/addon_manager.rb:117:in `yield_addon_with_retry'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-2.0.2/lib/pharos/addon_manager.rb:104:in `block in each'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-2.0.2/lib/pharos/addon_manager.rb:134:in `block in with_enabled_addons'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-2.0.2/lib/pharos/addon_manager.rb:131:in `each'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-2.0.2/lib/pharos/addon_manager.rb:131:in `with_enabled_addons'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-2.0.2/lib/pharos/addon_manager.rb:100:in `each'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-2.0.2/lib/pharos/cluster_manager.rb:175:in `apply_addons'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-2.0.2/lib/pharos/up_command.rb:44:in `configure'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-2.0.2/lib/pharos/up_command.rb:20:in `block in execute'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-2.0.2/lib/pharos/up_command.rb:19:in `chdir'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-2.0.2/lib/pharos/up_command.rb:19:in `execute'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/clamp-1.2.1/lib/clamp/command.rb:63:in `run'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-2.0.2/lib/pharos/command.rb:16:in `run'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/clamp-1.2.1/lib/clamp/subcommand/execution.rb:11:in `execute'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/clamp-1.2.1/lib/clamp/command.rb:63:in `run'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-2.0.2/lib/pharos/command.rb:16:in `run'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/clamp-1.2.1/lib/clamp/command.rb:132:in `run'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-2.0.2/bin/pharos-cluster:13:in `<top (required)>'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/bin/pharos-cluster:23:in `load'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/bin/pharos-cluster:23:in `<main>'
    retrying after 128 seconds ...
```

**What you expected to happen**:

Upgrade should proceed without any issues

**How to reproduce it (as minimally and precisely as possible)**:

A) install version 2.0.0 and try upgrading to 2.0.2/2.0.3
B) install version 2.0.0, upgrade to 2.0.1 and try upgrading to 2.0.2/2.0.3 (my current state)

**Anything else we need to know?**:

no

**Environment**:
- Pharos version: 2.0.2
- Cloud provider or hardware configuration: scaleway + terraform
- OS (e.g. from /etc/os-release; both for the client and for the used nodes): debian stretch
- Others: running macos high sierra

**cluster.yml:**

```
network:
  provider: weave
  pod_network_cidr: 172.31.0.0/16
  service_cidr: 172.32.0.0/16
  weave:
    trusted_subnets:
      - '10.133.0.0/16'
addons:
  ingress-nginx:
    enabled: true
  helm:
    enabled: true
  kontena-lens:
    enabled: true
    name: xxx
    host: 'xxx'
    tls:
      email: 'jakub.knejzlik@gmail.com'
  cert-manager:
    enabled: true
    issuer:
      name: letsencrypt-prod
      server: https://acme-v02.api.letsencrypt.org/directory
      email: jakub.knejzlik@gmail.com
```

**Comment by jakubknejzlik** [comment]
Workaround works, thanks for such a quick reply! 👍

**Comment by jnummelin** [comment]
this is fixed in downstream k8s-client
