### ISSUE TITLE
Validate cluster version fails if public ip of the master has changed

### ISSUE THREAD

**Issue by nevalla** [kontena/pharos-cluster#847]
When public ip address of the master node has changed and updating the cluster with updated cluster.yml, `pharos up` fails when validating cluster version because of outdated SSL certificate:
```
==> Validate cluster version @ master-01
    [master] got error (Excon::Error::Socket): hostname "xx.xxx.xx.xx" does not match the server certificate (OpenSSL::SSL::SSLError)
/__enclose_io_memfs__/lib/ruby/2.4.0/openssl/ssl.rb:291:in `post_connection_check'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/excon-0.62.0/lib/excon/ssl_socket.rb:133:in `initialize'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/excon-0.62.0/lib/excon/connection.rb:429:in `new'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/excon-0.62.0/lib/excon/connection.rb:429:in `socket'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/excon-0.62.0/lib/excon/connection.rb:111:in `request_call'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/excon-0.62.0/lib/excon/middlewares/mock.rb:48:in `request_call'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/excon-0.62.0/lib/excon/middlewares/instrumentor.rb:26:in `request_call'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/excon-0.62.0/lib/excon/middlewares/base.rb:16:in `request_call'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/excon-0.62.0/lib/excon/middlewares/base.rb:16:in `request_call'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/excon-0.62.0/lib/excon/middlewares/base.rb:16:in `request_call'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/excon-0.62.0/lib/excon/middlewares/base.rb:16:in `request_call'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/excon-0.62.0/lib/excon/connection.rb:260:in `request'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/k8s-client-0.4.2/lib/k8s/transport.rb:207:in `request'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/k8s-client-0.4.2/lib/k8s/transport.rb:281:in `get'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/k8s-client-0.4.2/lib/k8s/api_client.rb:49:in `api_resources!'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/k8s-client-0.4.2/lib/k8s/api_client.rb:58:in `api_resources'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/k8s-client-0.4.2/lib/k8s/api_client.rb:66:in `resource'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-2.0.2/lib/pharos/phases/validate_version.rb:63:in `previous_config_map'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-2.0.2/lib/pharos/phases/validate_version.rb:18:in `call'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-2.0.2/lib/pharos/phase_manager.rb:92:in `block in apply'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-2.0.2/lib/pharos/phase_manager.rb:53:in `yield_phase_with_retry'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-2.0.2/lib/pharos/phase_manager.rb:44:in `block in run_serial'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-2.0.2/lib/pharos/phase_manager.rb:43:in `map'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-2.0.2/lib/pharos/phase_manager.rb:43:in `run_serial'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-2.0.2/lib/pharos/phase_manager.rb:73:in `run'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-2.0.2/lib/pharos/phase_manager.rb:89:in `apply'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-2.0.2/lib/pharos/cluster_manager.rb:171:in `apply_phase'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-2.0.2/lib/pharos/cluster_manager.rb:76:in `validate'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-2.0.2/lib/pharos/up_command.rb:34:in `configure'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-2.0.2/lib/pharos/up_command.rb:20:in `block in execute'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-2.0.2/lib/pharos/up_command.rb:19:in `chdir'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-2.0.2/lib/pharos/up_command.rb:19:in `execute'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/clamp-1.2.1/lib/clamp/command.rb:63:in `run'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-2.0.2/lib/pharos/command.rb:16:in `run'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/clamp-1.2.1/lib/clamp/subcommand/execution.rb:11:in `execute'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/clamp-1.2.1/lib/clamp/command.rb:63:in `run'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-2.0.2/lib/pharos/command.rb:16:in `run'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/clamp-1.2.1/lib/clamp/command.rb:132:in `run'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-2.0.2/bin/pharos-cluster:13:in `<top (required)>'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/bin/pharos-cluster:23:in `load'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/bin/pharos-cluster:23:in `<main>'
```

Edit: Added backtrace

**Comment by jakolehm** [comment]
Note: ssl certificates are automatically re-generated after the validation...
